fuxingloh/vue-horizontal

.github/release-drafter.yml, README.md, babel.config.js, package-lock.json, package.json, src/vue-horizontal.vue
=> feat: Refactored and Simplified vue-horizontal.vue implementation

package-lock.json, package.json
=> chore: Add size-limit dependency

.editorconfig, .github/auto_assign.yml, .github/workflows/ci.yml, dev/components/empty.vue, dev/components/index.ts, dev/components/simple.vue, dev/index.vue, dev/serve.ts, dev/serve.vue, package-lock.json, package.json, src/vue-horizontal.vue
=> chore: Refactor serve/dev for easy development and testing

README.md, babel.config.js, cypress/integration/simple.spec.js, dev/components/content-box.vue, dev/components/index.ts, dev/components/simple.vue, dev/index.vue, dev/serve.vue, package.json, src/vue-horizontal.vue
=> fix: Firefox failing E2E

README.md, docs/components/global/caniuse.vue, docs/content/en/advanced.md, docs/content/en/basic.md, docs/content/en/index.md, docs/content/en/installation.md, docs/content/en/limitations.md, docs/content/en/recipes-control/carousel.md, docs/content/en/recipes-control/drag.md, docs/content/en/recipes-control/navigation.md, docs/content/en/recipes-control/scrollbar.md, docs/content/en/recipes-control/snapping.md, docs/content/en/recipes-design/cards.md, docs/content/en/recipes-design/circle.md, docs/content/en/recipes-design/mobile.md, docs/content/en/recipes-design/responsive.md, docs/content/en/recipes-design/slanted.md, docs/content/en/recipes.md, docs/content/en/taxonomy.md, docs/nuxt.config.js, docs/package-lock.json, docs/package.json
=> docs: Introduction, Setup and Limitations

.eslintrc.js, README.md, src/vue-horizontal.vue
=> feat: Freezing CCS with v-hl- for internals

cypress/integration/functional/event.spec.js, cypress/integration/functional/nav-button.spec.js, cypress/integration/functional/scroll-to-index.spec.js, cypress/integration/functional/simple.spec.js, cypress/integration/functional/snapping.spec.js, cypress/integration/visual/scroll-to-index.spec.js, cypress/integration/visual/simple.spec.js, dev/components/event.vue, dev/components/index.ts, src/vue-horizontal.vue
=> feat: Added events: next, prev, scroll and scroll-debounce

cypress/integration/functional/responsive.spec.js, dev/components/index.ts, dev/components/responsive.vue, src/vue-horizontal.vue
- Optional
- Disabled by default
=> feat: Added opinionated responsive classes (disabled by default)

cypress/integration/functional/simple.spec.js, cypress/integration/functional/snapping.spec.js, dev/components/snapping.vue, src/vue-horizontal.vue
=> feat: snap start/center/end and .v-hl-btn internals

cypress/integration/functional/content-width.spec.js, cypress/integration/functional/event.spec.js, dev/components/event.vue, src/vue-horizontal.vue
=> fix: nav-btn will not overscroll content that are only half visible

src/vue-horizontal.vue
=> fix: nav button css should not influence slots css

README.md, docs/content/en/index.md, docs/content/en/installation.md
=> docs: unpkg.com/vue-horizontal

src/vue-horizontal.vue
=> fix: undefined slots due use of template

src/vue-horizontal.vue
=> fix: svg to fill current color so that it can be easily edited in CSS

cypress/integration/functional/content-overflow.spec.js, cypress/integration/functional/event.spec.js, cypress/integration/functional/move.spec.js, dev/components/content-overflow.vue, dev/components/event.vue, dev/components/index.ts, dev/components/move.vue, src/vue-horizontal.vue
=> feat: Using more consistent prev/next nav btn with index navigation

dev/components/move.vue, src/vue-horizontal.vue
=> chore: Renamed move to displacement for accuracy

src/vue-horizontal.vue
=> chore: Optimized slots navigation performance

README.md, docs/components/global/placeholder-component-design.vue, docs/components/global/placeholder-component.vue, docs/content/en/design/navigation.md, docs/content/en/design/scrollbar.md, docs/content/en/design/taxonomy.md, docs/content/en/features.md, docs/content/snippets/design/design-navigation-above.vue, docs/content/snippets/design/design-navigation-customize.vue, docs/content/snippets/design/design-navigation-small.vue, docs/content/snippets/design/design-navigation-tiny.vue, docs/content/snippets/design/design-navigation.vue, docs/content/snippets/design/design-scrollbar-customize.vue, docs/content/snippets/features/features-event-prev-next.vue, docs/content/snippets/features/features-scroll-displacement.vue, docs/nuxt.config.js, docs/package-lock.json, docs/package.json, docs/plugins/smoothscroll.client.ts, tsconfig.json
=> docs: navigation.md

src/vue-horizontal.vue
=> fix: rename 'debouceId' to 'debounceId'

docs/content/en/features.md, src/vue-horizontal.vue
=> feat: scrollToLeft with behavior option

docs/components/global/recipes-list.vue, docs/content/en/features.md, docs/content/en/index.md, docs/content/en/recipes/about.md, docs/content/en/recipes/autoplay.md, docs/content/en/recipes/card.md, docs/content/en/recipes/dragging.md, docs/content/snippets/design/design-navigation-above.vue, docs/content/snippets/design/design-navigation-tiny.vue, docs/content/snippets/features/features-css-btn.vue, docs/content/snippets/features/features-css-container.vue, docs/content/snippets/features/features-event-prev-next.vue, docs/content/snippets/features/features-method-prev-next.vue, docs/content/snippets/features/features-method-scroll-index.vue, docs/content/snippets/features/features-method-scroll-left.vue, docs/content/snippets/features/features-nav-button-disable.vue, docs/content/snippets/features/features-nav-button-slot.vue, docs/content/snippets/features/features-scroll-bar.vue, docs/content/snippets/features/features-scroll-displacement.vue, docs/content/snippets/features/features-scroll-snapping-center.vue, docs/content/snippets/features/features-scroll-snapping-none.vue, docs/content/snippets/features/features-scroll-snapping-start.vue, docs/content/snippets/recipes/dragging/recipes-dragging.vue
=> docs: dragging.md

README.md, docs/content/en/recipes/autoplay.md, docs/content/en/recipes/cards.md, docs/content/en/recipes/dragging.md, docs/content/snippets/recipes/autoplay/recipes-autoplay-forward-reset.vue, docs/content/snippets/recipes/autoplay/recipes-autoplay-forward-reverse.vue, docs/content/snippets/recipes/autoplay/recipes-autoplay-initial.vue, docs/content/snippets/recipes/autoplay/recipes-autoplay-mirror.vue, docs/content/snippets/recipes/autoplay/recipes-autoplay-peeking.vue, docs/content/snippets/recipes/autoplay/recipes-autoplay-tracking.vue, docs/nuxt.config.js
=> docs: autoplay.md

dev/components/nav-button.vue, docs/components/global/caniuse.vue, docs/content/snippets/design/design-navigation-customize.vue, docs/content/snippets/features/features-nav-button-slot.vue
=> chore: refactor slot to v-slot as former is deprecated

.eslintrc.js, .github/workflows/ci-ssg.yml, .github/workflows/ci-ssr.yml, README.md, cypress/integration/functional/event.spec.js, docs/content/en/features.md, src/vue-horizontal.vue, tsconfig.json
=> chore: internals optimization

cypress/integration/functional/nav-button.spec.js, cypress/integration/functional/responsive.spec.js, dev/components/nav-button.vue, docs/content/en/features.md, docs/content/snippets/features/features-nav-button-between.vue, docs/nuxt.config.js, src/vue-horizontal.vue
=> feat: better button extendability and accessibility

docs/content/en/recipes/tabs.md, docs/content/snippets/recipes/tabs/recipes-tabs-simple.vue, docs/nuxt.config.js
=> docs: tabs.md

docs/components/global/snippet-mock-browser.vue, docs/content/en/recipes/banner.md, docs/content/en/recipes/tabs.md, docs/content/en/recipes/tags.md, docs/content/snippets/recipes/banner/recipes-banner-1-3.vue, docs/content/snippets/recipes/banner/recipes-banner-1-5.vue, docs/content/snippets/recipes/banner/recipes-banner-2-8.vue, docs/content/snippets/recipes/tabs/recipes-tabs-sides.vue, docs/content/snippets/recipes/tags/recipes-tags-full.vue, docs/content/snippets/recipes/tags/recipes-tags-tight.vue
=> docs: tags.md

docs/content/en/recipes/avatar.md, docs/content/snippets/recipes/avatar/recipes-avatar-large.vue, docs/content/snippets/recipes/avatar/recipes-avatar-small.vue
=> docs: avatar.md

docs/components/global/snippet-mock-browser.vue, docs/content/en/index.md, docs/nuxt.config.js, src/vue-horizontal.vue
chore: generate cache disable, due to build fails
chore: added will-change to snippet-mock-browser for better CSS performance
=> chore: debounce changed to 100ms

src/vue-horizontal.vue
=> fix: undefined computed slots

docs/components/global/placeholder-header.vue, docs/components/global/snippet-mock-browser.vue, docs/content/en/recipes/carousel.md, docs/content/snippets/others/autoplay/recipes-autoplay-peeking.vue, docs/content/snippets/recipes/carousel/recipes-carousel-full.vue
=> docs: carousel.md

docs/assets/img/index.ts, docs/content/en/recipes/avatar.md, docs/content/en/recipes/banner.md, docs/content/en/recipes/carousel.md, docs/content/en/recipes/square.md, docs/content/en/recipes/tags.md, docs/content/snippets/recipes/square/recipes-square-album.vue
=> docs: square.md

docs/assets/img/index.ts, docs/content/en/recipes/cards.md, docs/content/snippets/recipes/avatar/recipes-avatar-large.vue, docs/content/snippets/recipes/avatar/recipes-avatar-small.vue, docs/content/snippets/recipes/banner/recipes-banner-1-3.vue, docs/content/snippets/recipes/banner/recipes-banner-1-5.vue, docs/content/snippets/recipes/banner/recipes-banner-2-8.vue, docs/content/snippets/recipes/cards/recipes-cards-news-fixed.vue, docs/content/snippets/recipes/cards/recipes-cards-news.vue, docs/content/snippets/recipes/cards/recipes-cards-repository.vue, docs/content/snippets/recipes/cards/recipes-cards-videos-aside.vue, docs/content/snippets/recipes/recipes-default.vue
=> docs: cards.md

README.md, docs/content/en/recipes/cards.md, docs/content/en/recipes/rectangle.md, docs/content/snippets/recipes/cards/recipes-cards-slanted.vue
=> docs: cards.md slanted

docs/content/en/others/dragging.md, docs/content/snippets/recipes/avatar/recipes-avatar-large.vue, docs/content/snippets/recipes/banner/recipes-banner-1-3.vue, docs/content/snippets/recipes/banner/recipes-banner-1-5.vue, docs/content/snippets/recipes/banner/recipes-banner-2-8.vue, docs/content/snippets/recipes/cards/recipes-cards-news-fixed.vue, docs/content/snippets/recipes/cards/recipes-cards-news.vue, docs/content/snippets/recipes/cards/recipes-cards-repository.vue, docs/content/snippets/recipes/cards/recipes-cards-slanted.vue, docs/content/snippets/recipes/cards/recipes-cards-videos-aside.vue, docs/content/snippets/recipes/recipes-fixed.vue, docs/content/snippets/recipes/recipes-responsive.vue, docs/content/snippets/recipes/rectangle/recipes-rectangle-half.vue, docs/content/snippets/recipes/rectangle/recipes-rectangle-responsive.vue, docs/content/snippets/recipes/rectangle/recipes-rectangle-tall.vue, src/vue-horizontal.vue
=> chore: minor refactor and comment

docs/content/en/recipes/tags.md, docs/content/snippets/others/autoplay/recipes-autoplay-tracking.vue, docs/content/snippets/others/dragging/recipes-dragging.vue, docs/content/snippets/recipes/tags/recipes-tags-scroll-wheel.vue
=> docs: tags.md with mouse wheel event

docs/tailwind.config.js
=> docs: Added missing content snippets purge

docs/content/en/recipes/cards.md, docs/content/snippets/recipes/cards/recipes-cards-dark.vue
=> docs: dark theme card recipe

.github/labeler.yml, .imgbotconfig, docs/static/robots.txt
=> chore: added .imgbotconfig and robots.txt

src/vue-horizontal.vue
=> fix: removed margin for last child in container

.browserslistrc, build/rollup.config.js, package-lock.json, package.json
=> chore: moved browserslist config to package.json

.github/labeler.yml, .github/workflows/pr-triage.yml
=> chore: updated to use a faster labeler 'fuxingloh/multi-labeler'

.github/labeler.yml, .github/workflows/pr-triage.yml
=> chore: added checks for semantic pull request

src/vue-horizontal.vue
=> fix: v-hl-responsive last-child wrong parent class

docs/content/en/recipes/pagination.md, docs/content/snippets/recipes/pagination/recipes-pagination.vue
Inspired by https://github.com/fuxingloh/vue-horizontal/issues/89
=> docs: added a simple example on how you could do pagination

src/vue-horizontal.vue
=> fix: hover not required for cursor pointer

README.md
=> docs: Added vue 3 install instruction

src/vue-horizontal.vue
Fixes #99 
However with or without the change all cypress tests seem to fail.
=> Fix on scroll after unmount 

src/vue-horizontal.vue
Temporary fix for https://github.com/fuxingloh/vue-horizontal/issues/99#issue-862691647
=> Fix on scroll called after component is unmounted
